name: Pull Request
description: Create a pull request to help us improve
title: "[PR]"
body:
- type: checkboxes
  attributes:
    label: Checklist
    description: Please ensure you've completed all of the following.
    options:
    - label: I have read the [contribution guidelines](https://github.com/Azure-Samples/app-service-javascript-sap-cloud-sdk-quickstart/blob/main/CONTRIBUTING.md).
      required: true
- type: textarea
  attributes:
    label: What is the purpose of this pull request?
    placeholder: Describe the intention of the changes being proposed. What problem does it solve or functionality does it add?
  validations:
    required: true
- type: dropdown
  attributes:
    label: Does this introduce a breaking change?
    description: Does the PR introduce any breaking changes?
    options:
    - Yes
    - No
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Pull Request Type
    description: What kind of change does this Pull Request introduce?
    options:
    - label: Bugfix
    - label: Feature
    - label: Code style update (formatting, local variables)
    - label: Refactoring (no functional changes, no api changes)
    - label: Documentation content changes
  validations:
    required: true
- type: textarea
  attributes:
    label: How to test?
    description: Provide a description of how to test the PR.
    placeholder: |
      1. Get the code
      2. git clone [repo-address]
      3. cd [repo-name]
      4. git checkout [branch-name]
      5. npm install
      6. ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Test the code
    description: Add steps to run the tests suite and/or manually test 
  validations:
    required: false
- type: textarea
  attributes:
    label: What to check?
    description: What should be checked?
    placeholder: |
      * Verify that the following are valid
      * ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Other Information
    description: |
      Add any other helpful information that may be needed here.

      Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
