trigger:
  - main

ool:
  vmImage: ubuntu-latest

steps:
  - task: setup-azd@0
    displayName: Install azd

  - pwsh: |
      $info = $Env:AZURE_CREDENTIALS | ConvertFrom-Json -AsHashtable;

      azd auth login `
        --client-id "$($info.clientId)" `
        --client-secret "$($info.clientSecret)" `
        --tenant-id "$($info.tenantId)"
    displayName: azd login
    env:
      AZURE_CREDENTIALS: $(AZURE_CREDENTIALS)

  - task: AzureCLI@2
    displayName: Azure Dev Provision
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd provision --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      RS_RESOURCE_GROUP: $(RS_RESOURCE_GROUP)
      RS_STORAGE_ACCOUNT: $(RS_STORAGE_ACCOUNT)
      RS_CONTAINER_NAME: $(RS_CONTAINER_NAME)
      ODATA_URL: $(ODATA_URL)
      ODATA_USERNAME: $(ODATA_USERNAME)
      ODATA_USERPWD: $(ODATA_USERPWD)
      APIKEY: $(APIKEY)
      APIKEY_HEADERNAME: $(APIKEY_HEADERNAME)

  - task: AzureCLI@2
    displayName: Azure Dev Deploy
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd deploy --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
      ODATA_URL: $(ODATA_URL)
      ODATA_USERNAME: $(ODATA_USERNAME)
      ODATA_USERPWD: $(ODATA_USERPWD)
      APIKEY: $(APIKEY)
      APIKEY_HEADERNAME: $(APIKEY_HEADERNAME)
