#!/bin/bash

# This script is part of the sample's workflow for configuring App Registrations
# in Azure AD and saving the appropriate values in Key Vault, and Azure App Config Service
# so that the application can authenticate users. Note that an app registration is
# something you'll want to set up once, and reuse for every version of the web app
# that you deploy. You can learn more about app registrations at
# https://learn.microsoft.com/en-us/azure/active-directory/develop/application-model
#
# If you do not have permission to create App Registrations consider
# sharing this script, or something similar, with your administrators to help them
# set up the variables you need to integrate with Azure AD
#
# This code may be repurposed for your scenario as desired
# but is not covered by the guidance in this content.

# Using Azure CLI command to create an app registration on Entra ID: https://learn.microsoft.com/cli/azure/ad/app?view=azure-cli-latest
# ToDo: pass azd generated app name via script parameter
SAP_SDK_APP_NAME='app-api-xosbg'

echo "Creating app registration for web app and retrieving object id..."
# Create app registration for web app: https://learn.microsoft.com/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-create
OBJECT_ID=$(az ad app create --display-name $SAP_SDK_APP_NAME --enable-id-token-issuance true --sign-in-audience 'AzureADMyOrg' --web-redirect-uris 'https://${SAP_SDK_APP_NAME}.azurewebsites.net/.auth/login/aad/callback' --required-resource-accesses @resource-scope.json  --query "{id:id}" -o tsv)

# Override default app registration setting for access token version to support Entra ID v2 endpoints. BE AWARE the new token audience will start showing after the next refresh cycle -> worst case: several hours.
az rest --method PATCH --headers "Content-Type=application/json" --uri https://graph.microsoft.com/v1.0/applications/$OBJECT_ID --body '{"api":{"requestedAccessTokenVersion": 2}}'
# Add default API permission User.Read to app registration: https://learn.microsoft.com/cli/azure/ad/app/permission?view=azure-cli-latest
az ad app permission add --id $OBJECT_ID --api 00000003-0000-0000-c000-000000000000 --api-permissions e1fe6dd8-ba31-4d61-89e7-88639da4683d=Scope
# Create Service Princiapal to Grant permissions
SP_ID=$(az ad sp create --id $OBJECT_ID --query "{id:id}" -o tsv)
# Grant permissions using service principal to activate permissions
#Fixme: This is not working
#az ad app permission grant --id $OBJECT_ID --api 00000003-0000-0000-c000-000000000000 --scope User.Read --principal-id $SP_ID

# Create secret for app registration
NEW_SECRET=$(az ad app credential reset --id $OBJECT_ID --append --display-name 'Generated by AZD' --query "{password:password}" -o tsv)

#ToDo: Store secret in key vault

# all done
exit 0